defmodule PrismaticCodegen.Render.ElixirSDK.DocTree do
  @moduledoc """
  Generated markdown reference-doc tree for provider SDKs.
  """

  alias PrismaticCodegen.ProviderIR
  alias PrismaticCodegen.RenderedFile

  @spec render(ProviderIR.t()) :: [RenderedFile.t()]
  def render(%ProviderIR{} = ir) do
    [
      docs_file(ir, docs_root_readme_path(ir), render_root_readme(ir)),
      docs_file(ir, provider_overview_path(ir), render_provider_overview(ir)),
      docs_file(ir, operations_index_path(ir), render_operations_index(ir))
    ] ++
      Enum.map(
        ir.operations,
        &docs_file(ir, operation_path(ir, &1), render_operation_page(ir, &1))
      ) ++
      [
        docs_file(ir, models_index_path(ir), render_models_index(ir))
      ] ++
      Enum.map(ir.models, &docs_file(ir, model_path(ir, &1), render_model_page(ir, &1))) ++
      [
        docs_file(ir, enums_index_path(ir), render_enums_index(ir))
      ] ++
      Enum.map(ir.enums, &docs_file(ir, enum_path(ir, &1), render_enum_page(ir, &1)))
  end

  @spec artifact_paths(ProviderIR.t()) :: [Path.t()]
  def artifact_paths(%ProviderIR{} = ir) do
    [
      docs_root_readme_path(ir),
      provider_overview_path(ir),
      operations_index_path(ir)
    ] ++
      Enum.map(ir.operations, &operation_path(ir, &1)) ++
      [models_index_path(ir)] ++
      Enum.map(ir.models, &model_path(ir, &1)) ++
      [enums_index_path(ir)] ++
      Enum.map(ir.enums, &enum_path(ir, &1))
  end

  defp docs_file(ir, path, content) do
    %RenderedFile{
      path: path,
      kind: :docs,
      content: render_generated_banner(ir) <> "\n\n" <> String.trim(content)
    }
  end

  defp render_generated_banner(_ir) do
    """
    <!-- Generated by prismatic_codegen. Do not edit by hand. -->
    """
    |> String.trim()
  end

  defp render_root_readme(%ProviderIR{} = ir) do
    """
    # Generated Reference

    This reference tree is generated from curated GraphQL documents and the provider schema snapshot.

    ## Contents

    - [Provider Overview](provider.md)
    - [Operations](operations/README.md) (#{length(ir.operations)})
    - [Models](models/README.md) (#{length(ir.models)})
    - [Enums](enums/README.md) (#{length(ir.enums)})
    """
    |> String.trim()
  end

  defp render_provider_overview(%ProviderIR{} = ir) do
    """
    # Provider Overview

    ## Runtime Defaults

    - Provider name: `#{ir.provider.name}`
    - Namespace module: `#{inspect(ir.provider.namespace)}`
    - Client module: `#{inspect(ir.provider.client_module)}`
    - Base URL: `#{ir.provider.base_url}`

    ## Auth Metadata

    ```elixir
    #{inspect(ir.provider.auth, pretty: true, limit: :infinity)}
    ```

    ## Generated Surface

    - Curated documents: #{length(ir.documents)}
    - Operations: #{length(ir.operations)}
    - Models: #{length(ir.models)}
    - Enums: #{length(ir.enums)}
    """
    |> String.trim()
  end

  defp render_operations_index(%ProviderIR{} = ir) do
    rows =
      Enum.map_join(ir.operations, "\n", fn operation ->
        "| [#{operation.name}](#{Path.basename(operation_path(ir, operation))}) | `#{operation.operation.kind}` | `#{operation.document.root_field}` | `#{inspect(operation.module)}` | `#{operation.response_type}` | `#{operation.document.relative_path}` |"
      end)

    """
    # Operations

    | Name | Kind | Root Field | Module | Response Type | Source Document |
    | --- | --- | --- | --- | --- | --- |
    #{rows}
    """
    |> String.trim()
  end

  defp render_operation_page(%ProviderIR{} = _ir, %ProviderIR.Operation{} = operation) do
    typed_section =
      case operation.model_module do
        nil ->
          nil

        model_module ->
          """
          ## Typed Response

          The typed root object is returned as `#{inspect(model_module)}`.

          ```elixir
          {:ok, response} = #{inspect(operation.module)}.call_typed(client)
          typed_root = response.data
          ```
          """
      end

    sections =
      [
        """
        # #{operation.name}

        ## Summary

        - Kind: `#{operation.operation.kind}`
        - Root field: `#{operation.document.root_field}`
        - Module: `#{inspect(operation.module)}`
        - Response type: `#{operation.response_type}`
        - Source document: `#{operation.document.relative_path}`

        ## Execute

        ```elixir
        {:ok, response} = #{inspect(operation.module)}.call(client)
        ```
        """,
        typed_section,
        """
        ## GraphQL Document

        ```graphql
        #{String.trim(operation.document.document)}
        ```
        """
      ]
      |> Enum.reject(&is_nil/1)

    Enum.join(sections, "\n\n")
  end

  defp render_models_index(%ProviderIR{} = ir) do
    rows =
      Enum.map_join(ir.models, "\n", fn model ->
        "| [#{model.name}](#{Path.basename(model_path(ir, model))}) | `#{inspect(model.module)}` | #{length(model.fields)} |"
      end)

    """
    # Models

    | Name | Module | Field Count |
    | --- | --- | --- |
    #{rows}
    """
    |> String.trim()
  end

  defp render_model_page(%ProviderIR{} = ir, %ProviderIR.Model{} = model) do
    field_rows =
      Enum.map_join(model.fields, "\n", fn field ->
        "| `#{field.name}` | `:#{field.key}` | `#{field.kind}` | #{field_type_label(ir, field)} |"
      end)

    """
    # #{model.name}

    ## Summary

    - Module: `#{inspect(model.module)}`
    - Field count: #{length(model.fields)}

    ## Fields

    | GraphQL Field | Elixir Key | Kind | Type |
    | --- | --- | --- | --- |
    #{field_rows}
    """
    |> String.trim()
  end

  defp render_enums_index(%ProviderIR{} = ir) do
    rows =
      Enum.map_join(ir.enums, "\n", fn enum ->
        "| [#{enum.name}](#{Path.basename(enum_path(ir, enum))}) | `#{inspect(enum.module)}` | #{length(enum.values)} |"
      end)

    """
    # Enums

    | Name | Module | Value Count |
    | --- | --- | --- |
    #{rows}
    """
    |> String.trim()
  end

  defp render_enum_page(_ir, %ProviderIR.Enum{} = enum) do
    values = Enum.map_join(enum.values, "\n", &"- `#{&1}`")

    """
    # #{enum.name}

    ## Summary

    - Module: `#{inspect(enum.module)}`
    - Value count: #{length(enum.values)}

    ## Values

    #{values}
    """
    |> String.trim()
  end

  defp field_type_label(%ProviderIR{} = ir, %ProviderIR.Model.Field{} = field) do
    cond do
      field.kind == "ENUM" ->
        enum =
          Enum.find(ir.enums, fn enum ->
            enum.name == field.type_name
          end)

        if enum do
          "[`#{field.type_name}`](../enums/#{Path.basename(enum_path(ir, enum))})"
        else
          "`#{field.type_name}`"
        end

      field.kind == "OBJECT" ->
        model =
          Enum.find(ir.models, fn model ->
            model.name == field.type_name
          end)

        if model do
          "[`#{field.type_name}`](#{model_link(ir, model)})"
        else
          "`#{field.type_name}`"
        end

      true ->
        "`#{field.type_name}`"
    end
  end

  defp model_link(ir, model) do
    if Path.dirname(model_path(ir, model)) == Path.dirname(models_index_path(ir)) do
      Path.basename(model_path(ir, model))
    else
      "../models/#{Path.basename(model_path(ir, model))}"
    end
  end

  defp docs_root_readme_path(%ProviderIR{} = ir) do
    Path.join(ir.provider.output.docs_root, "README.md")
  end

  defp provider_overview_path(%ProviderIR{} = ir) do
    Path.join(ir.provider.output.docs_root, "provider.md")
  end

  defp operations_index_path(%ProviderIR{} = ir) do
    Path.join([ir.provider.output.docs_root, "operations", "README.md"])
  end

  defp operation_path(%ProviderIR{} = ir, %ProviderIR.Operation{} = operation) do
    Path.join([ir.provider.output.docs_root, "operations", "#{operation.id}.md"])
  end

  defp models_index_path(%ProviderIR{} = ir) do
    Path.join([ir.provider.output.docs_root, "models", "README.md"])
  end

  defp model_path(%ProviderIR{} = ir, %ProviderIR.Model{} = model) do
    Path.join([ir.provider.output.docs_root, "models", "#{Macro.underscore(model.name)}.md"])
  end

  defp enums_index_path(%ProviderIR{} = ir) do
    Path.join([ir.provider.output.docs_root, "enums", "README.md"])
  end

  defp enum_path(%ProviderIR{} = ir, %ProviderIR.Enum{} = enum) do
    Path.join([ir.provider.output.docs_root, "enums", "#{Macro.underscore(enum.name)}.md"])
  end
end
